#!/bin/bash

set -e

GAMEDIR=$SNAP_USER_DATA/saves_and_config
if [ ! -d $GAMEDIR ];
then
  echo "Game directory doesn't exist"
  echo "Creating directory"
  mkdir -p $GAMEDIR
fi

cd ${SNAP}
${SNAP}/bin/gzdoom -iwad ${SNAP}/boa.ipk3 -config ${GAMEDIR}/boa.conf -savedir ${GAMEDIR}
