#!/bin/bash

set -e

GAMEDIR=$SNAP_USER_DATA/saves_and_config
if [ ! -d $GAMEDIR ];
then
  echo "Game directory doesn't exist"
  echo "Creating directory"
  mkdir -p $GAMEDIR
fi

cd ${SNAP}/share/games/doom
${SNAP}/bin/gzdoom -iwad ${SNAP}/boa.ipk3 -file lights.pk3 brightmaps.pk3 game_widescreen_gfx.pk3 -config ${GAMEDIR}/boa.conf -savedir ${GAMEDIR}
