name: boa
base: core20
version: git
summary: Wolfenstein - Blade of Agony
description: |
  A complete DOOM mod in the Wolfenstein style.
confinement: strict
grade: stable
compression: lzo

architectures:
  - build-on: amd64

apps:
  boa:
    command: launcher
    plugs: [desktop, desktop-legacy, unity7, audio-playback, opengl, network, joystick]
    extensions: [gnome-3-38]

parts:
  gzdoom:
    plugin: dump
    source: gzdoom/gzdoom.tar.gz
    stage-packages:
      - libsdl2-2.0-0
      - zlib1g
      - libbz2-1.0
      - libjpeg8
      - libjpeg-turbo8
      - libfluidsynth2
      - fluid-soundfont-gm
      - libgme0
      - libopenal1
      - libmpg123-0
      - libsndfile1
      - libwildmidi2
      - timidity
      - libgl1-mesa-glx
      - libgomp1

  mod:
    plugin: nil
    source: https://github.com/Realm667/WolfenDoom.git
    build-packages:
      - p7zip-full
    override-build: |
      7z a -tzip -mmt=on -mm=Deflate -mx=0 -ssc -xr@'tools/7za/7zExcludeList.txt' -x@'tools/7za/7zExcludeListDir.txt' boa.ipk3 *
      cp boa.ipk3 *.txt $SNAPCRAFT_PART_INSTALL

  launch:
    plugin: dump
    source: launcher

  cleanup:
    after: [launch, mod, gzdoom]
    plugin: nil
    build-snaps:
      - core20
      - gtk-common-themes
      - gnome-3-38-2004
    override-prime: |
      set -eux
      for snap in "core20" "gtk-common-themes" "gnome-3-38-2004"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -r "$SNAPCRAFT_PRIME/{}" \;
      done

