name: boa
base: core20
version: "3.0"
summary: Wolfenstein - Blade of Agony
description: |
  A complete DOOM mod in the Wolfenstein style.
confinement: strict
grade: stable
compression: lzo

architectures:
  - build-on: amd64

apps:
  boa:
    command: launcher
    plugs: [desktop, desktop-legacy, unity7, audio-playback, opengl, network, joystick]
    extensions: [gnome-3-38]

parts:
  gzdoom:
    # This is far from transparent, but as current version of gzdoom do not
    # compile under current version of snapcraft, I need to fall back on a blob
    # compiled, by me, elsewhere.
    plugin: dump
    source: gzdoom/gzdoom.tar.gz
    prime:
      - -lib/python3.8
    stage-packages:
      - libsdl2-2.0-0
      - zlib1g
      - libbz2-1.0
      - libjpeg8
      - libjpeg-turbo8
      - libfluidsynth2
      - fluid-soundfont-gm
      - libgme0
      - libopenal1
      - libmpg123-0
      - libsndfile1
      - libwildmidi2
      - timidity
      - libgl1-mesa-glx
      - libgomp1

  mod:
    plugin: nil
    source: https://github.com/Realm667/WolfenDoom.git
    source-tag: v3.0
    build-packages:
      - p7zip-full
    override-build: |
      7z a -tzip -mmt=on -mm=Deflate -mx=0 -ssc -xr@'tools/7za/7zExcludeList.txt' -x@'tools/7za/7zExcludeListDir.txt' boa.ipk3 *
      cp boa.ipk3 *.txt $SNAPCRAFT_PART_INSTALL

  launch:
    plugin: dump
    source: launcher
