name: boa
base: core20
version: git
summary: Wolfenstein - Blade of Agony
description: |
  A complete DOOM mod in the Wolfenstein style.
confinement: strict
grade: stable
compression: lzo

apps:
  boa:
    command: launcher
    plugs: [desktop, desktop-legacy, unity7, audio-playback, opengl, network, joystick]
    extensions: [gnome-3-38]

parts:
  gzdoom:
    plugin: cmake
    after: [zmusic]
    source: git://github.com/coelckers/gzdoom.git
    source-commit: 55ce0510c2b181b941d30778f29b83a06955bb56
    cmake-parameters:
      - -DNO_FMOD=ON
    build-packages:
      - g++
      - make
      - cmake
      - libsdl2-dev
      - libudev-dev
      - libudev1
      - zlib1g-dev
      - libbz2-dev
      - libjpeg-dev
      - libfluidsynth-dev
      - libgme-dev
      - libopenal-dev
      - libmpg123-dev
      - libsndfile1-dev
      - libwildmidi-dev
      - libgtk-3-dev
      - timidity
      - nasm
      - libgl1-mesa-dev
    stage-packages:
      - libsdl2-2.0-0
      - zlib1g
      - libbz2-1.0
      - libjpeg8
      - libjpeg-turbo8
      - libfluidsynth2
      - fluid-soundfont-gm
      - libgme0
      - libopenal1
      - libmpg123-0
      - libsndfile1
      - libwildmidi2
      - timidity
      - libgl1-mesa-glx
      - libgomp1

  zmusic:
    plugin: cmake
    source: https://github.com/coelckers/ZMusic.git
    source-tag: 1.1.3
    build-packages:
      - g++
      - libfluidsynth-dev
      - libgme-dev
      - libopenal-dev
      - libmpg123-dev
      - libsndfile1-dev
      - libwildmidi-dev
      - timidity

  mod:
    plugin: nil
    source: https://github.com/Realm667/WolfenDoom.git
    build-packages:
      - p7zip-full
    override-build: |
      7z a -tzip -mmt=on -mm=Deflate -mx=0 -ssc -xr@'tools/7za/7zExcludeList.txt' -x@'tools/7za/7zExcludeListDir.txt' boa.ipk3 *
      cp boa.ipk3 *.txt $SNAPCRAFT_PART_INSTALL

  launch:
    plugin: dump
    source: launcher

  cleanup:
    after: [launch, mod, gzdoom]
    plugin: nil
    build-snaps:
      - core20
      - gtk-common-themes
      - gnome-3-38-2004
    override-prime: |
      set -eux
      for snap in "core20" "gtk-common-themes" "gnome-3-38-2004"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -r "$SNAPCRAFT_PRIME/{}" \;
      done

