name: boa
base: core18
version: git
summary: Wolfendoom - Blade of Agony
description: |
  A complete DOOM mod in the Wolfenstein style.
confinement: strict
grade: stable

apps:
  boa:
    command: launcher
    plugs: [desktop, desktop-legacy, unity7, audio-playback, opengl, network, joystick]
    extensions: [gnome-3-28]

parts:
  gzdoom:
    plugin: cmake
    source: git://guthub.com/coelckers/gzdoom.git
    source-tag: g4.4.2
    configflags:
      - -DNO_FMOD=ON
    build-packages:
      - g++
      - make
      - cmake
      - libsdl2-dev
      - zlib1g-dev
      - libbz2-dev
      - libjpeg-dev
      - libfluidsynth-dev
      - libgme-dev
      - libopenal-dev
      - libmpg123-dev
      - libsndfile1-dev
      - libwildmidi-dev
      - libgtk-3-dev
      - timidity
      - nasm
      - libgl1-mesa-dev
    stage-packages:
      - libsdl2-2.0-0
      - zlib1g
      - libbz2-1.0
      - libjpeg8
      - libjpeg-turbo8
      - libfluidsynth1
      - fluid-soundfont-gm
      - libgme0
      - libopenal1
      - libmpg123-0
      - libsndfile1
      - libwildmidi2
      - timidity
      - libgl1-mesa-glx

  mod:
    plugin: nil
    source: https://github.com/Realm667/WolfenDoom.git
    build-packages:
      - p7zip-full
    override-build: |
      7z a -tzip -mnt=on -mm=LZMA -mx=9 -ssc -xr@'tools/7zExcludeList.txt' -x@'tools/7zExcludeListDir.txt' wolf_boa.pk3 *
      cp wolf_boa.pk3 *.txt $SNAPCRAFT_PART_INSTALL

  launch:
    plugin: dump
    source: launcher

  cleanup:
    after: [launch, mod, gzdoom]
    plugin: nil
    build-snaps:
      - core18
      - gtk-common-themes
      - gnome-3-28-1804
    override-prime: |
      set -eux
      for snap in "core18" "gtk-common-themes" "gnome-3-28-1804"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -r "$SNAPCRAFT_PRIME/{}" \;
      done

